CREATE TABLE rpv.dbo.tbl_ClinicalData (
	cID int NOT NULL,
	RADAR_NO int NOT NULL,
	DATE_CLIN_PIC smalldatetime,
	HEIGHT decimal(8,1),
	WEIGHT decimal(8,2),
	COURSE_DIS int,
	SYS_BP int,
	DIA_BP int,
	MAP_BP int,
	DIALYSIS_REQ int,
	DATE_BX smalldatetime,
	OEDEMA bit,
	ANAEMIA bit,
	HYPOVAL bit,
	FEVER bit,
	INFECTION bit,
	INFECTION_DETAIL nvarchar(50),
	INFECTION_TYPE nvarchar(50),
	THROMBOSIS bit,
	THROMBOSIS_DETAIL nvarchar(250),
	COMP_THROMBOSIS bit,
	COMP_THROMBOSIS_DETAIL text,
	PERITONITIS bit,
	PUL_OED bit,
	HTH_REQ_TMT bit,
	PREC_INF bit,
	PREC_INF_DETAIL nvarchar(150),
	CLIN_EV_CHR_INF bit,
	CLIN_EV_CHR_INF_DETAIL nvarchar(150),
	DIABETES smallint,
	URTICARIA smallint,
	RASH bit,
	RASH_DETAIL nvarchar(50),
	PART_LIPODYS bit,
	OPTHALM bit,
	OPTHALM_DETAIL nvarchar(50),
	IMMUNIS_TRIGGER bit,
	COMMENTS text,
	PHENOTYPE1 int,
	PHENOTYPE2 int,
	PHENOTYPE3 int,
	PHENOTYPE4 int,
	SIG_DIAG1 nvarchar(30),
	SIG_DIAG2 nvarchar(30),
	TX_LISTED bit,
	CKD_STAGE int,
	SEQ_NO int
);

