CREATE TABLE rpv.dbo.tbl_6Month (
	fuID int NOT NULL,
	RADAR_NO int,
	DATE_FUP datetime,
	RELAP_SINCE_LAST bit,
	RELAP_LEN int,
	VIRAL_TRIG int,
	IMMUN_TRIG int,
	OTHER_TRIG int,
	IMMUNOSUP_INC bit,
	IMMUNOSUP_DOSE int,
	IMMUNOSUP_DUR int,
	PLASMA_EXCH int,
	PLASMA_EXCH_NO int,
	RESPONSE_TO int,
	MAX_PR_CREAT_RATIO int,
	MIN_SER_ALB int,
	COMP1 int,
	COMP2 int,
	COMP3 int,
	COMP4 int,
	OTHER_COMP nvarchar(50),
	DATE_START_DIAL datetime,
	DIAL_TYPE int,
	DATE_TRANSPLANT datetime,
	TRANS_TYPE int,
	TRANS_RECURR bit,
	DATE_TX_REJECT datetime,
	DATE_BX datetime,
	DATE_NEPHRECT datetime,
	DRUG1 nvarchar(50),
	DRUG2 nvarchar(50),
	DRUG3 nvarchar(50),
	DRUG4 nvarchar(50),
	DRUG5 nvarchar(50),
	DRUG6 nvarchar(50),
	SIG_CHANGE_STATUS nchar(10)
);
