#!/bin/sh
for i 
do
if [ -e $i ]
then
      gpgwrap -v -p /home/manager/scripts/fd gpg --batch --no-tty --decrypt -q $i > $i.xml 
      mv $i /home/manager/ibdfiles/dun
      mv $i.xml /usr/local/etc/ibdxml
fi
done
