#!/bin/sh
if [ -e /home/manager/ukt/.export/ukt_rpv_export.txt ]
then
      rm -rf /home/ukt/incoming/ukt_rpv_export.gpg
      gpg --output /home/ukt/incoming/ukt_rpv_export.gpg --encrypt --recipient <email-of-recipient> /home/manager/ukt/.export/ukt_rpv_export.txt
#      rm /home/manager/ukt/.export/ukt_rpv_export.txt
fi
