ALTER TABLE USER DROP PRIMARY KEY;

ALTER TABLE USER ADD id BIGINT(20)
NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE USER ADD COLUMN created DATETIME NOT NULL DEFAULT '2012-07-19 15:06:34';
ALTER TABLE USER ADD COLUMN updated DATETIME NOT NULL DEFAULT '2012-07-19 15:06:34';
ALTER TABLE USER ADD COLUMN deleted TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE patient ADD id BIGINT(20)
NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE comment ADD id BIGINT(20)
NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE diagnosis ADD id BIGINT(20)
NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE edtacode ADD id BIGINT(20)
NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;