ALTER TABLE aboutme MODIFY COLUMN id BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE centre ADD id BIGINT(20)
NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE comment MODIFY COLUMN id BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE diagnosis MODIFY COLUMN id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE edtacode DROP PRIMARY KEY;
ALTER TABLE edtacode ADD id BIGINT(20)
NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE edtacode ADD UNIQUE (edtaCode);

ALTER TABLE emailverification MODIFY COLUMN id BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE feedback MODIFY COLUMN id BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE letter MODIFY COLUMN id BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE log MODIFY COLUMN id BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE medicine MODIFY COLUMN id BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE news MODIFY COLUMN id BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE patient DROP PRIMARY KEY;
ALTER TABLE patient ADD id BIGINT(20)
NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE patient ADD UNIQUE INDEX (nhsno, centreCode);

ALTER TABLE result_heading DROP PRIMARY KEY;
ALTER TABLE result_heading ADD id BIGINT(20)
NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE result_heading ADD UNIQUE (headingcode);

ALTER TABLE splashpage MODIFY COLUMN id BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE splashpageuserseen MODIFY COLUMN id BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE testresult ADD id BIGINT(20)
NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE treatment DROP PRIMARY KEY;
ALTER TABLE treatment ADD id BIGINT(20)
NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE treatment ADD UNIQUE INDEX (nhsNo, treatmentCode);

ALTER TABLE uktcode MODIFY COLUMN id BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE uktstatus ADD id BIGINT(20)
NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER TABLE unit DROP PRIMARY KEY;
ALTER TABLE unit ADD id BIGINT(20)
NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE unit ADD UNIQUE (unitcode);

ALTER TABLE unitstat MODIFY COLUMN id BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE USER DROP PRIMARY KEY;
ALTER TABLE USER ADD id BIGINT(20)
NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST;
ALTER TABLE USER ADD UNIQUE (username);

ALTER TABLE userlog MODIFY COLUMN id BIGINT(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE usermapping MODIFY COLUMN id BIGINT(20) NOT NULL AUTO_INCREMENT;